[[section-introduction-and-goals]]
== Introduction and Goals
LoMap is a software system being developed as a university project. It is designed to help citizens create personalized maps of places and local businesses in their city.

The aim of the project is to develop a generic software solution that can be deployed and used in other cities as well. The system will allow users to add locations in different categories like shops, bars, restaurants, sights, monuments, etc. and show them in a map window. Users will also be able to add review scores, comments, pictures, and more about the added places. The shared information will be stored in a personal pod according to the SOLID project.

The project's initial focus is on the user, allowing them to create their personal map of the places they live. Users can manage the information that is accessible to either themselves or all of their friends. The system will allow users to see places and information about those places taken from their friends.

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Requirements Overview


*All LoMap* Users will be able to:

* [x] Add locations in different categories like shops, bars, restaurants, sights, monuments, etc.
* [x] Add review scores, comments, pictures, and more about the added places.
* [x] See places and information about those places taken from their friends
    ** Users will be able to decide, then, if their posts are shared with their friends only or remain accessible to themselves only.

In further of stages of the project:

* [x] _Establishment owners and public entities_ will be able to create public map locations for their businesses
* [x] _Users_ will be able to decide what city are the living in.
- [x] _Users_ will be able to personalized the set of friends the locations will be shared to.

Keeping privacy in mind, all of the above, will be supported by the **SOLID project specification **, making use of **SOLID Pods ** for individual data storage. This way, users will be in full control of *which* information they share *and of who* they are sharing it to.

_More details are described in the following document: https://arquisoft.github.io/course2223/labAssignmentDescription.html[LoMap Assigment Description]_

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

=== Quality Goals

|===
|Goal | Description | Example

|Privacy
| Data will only be shared with those parties the owner agrees to.
| The user pins his/her own home in the map, and wants it to remain private, and not accessible to other users.
It will be stored in his/her own POD, and won't be shared with any other user nor party.



|Responsiveness
|LoMap will adapt it's size and content distribution to the device it's being accessed to, so usability is ensured.
|User want's to know the general opinion of a local restaurant of a city she's visiting. She owns an old , small-screened phone, and so , LoMap contents will change their layout so this user can navigate successfully though it.



|===

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name| Contact |Expectations
|Product owners|

 José Emilio Labra Gayo, Pablo González González ,
Irene Cid Rico , Cristian Augusto Alonso

| They'll provide the project with architectural guidance, constraints and requirements.
| Citizen Users| - | To be able to intuitively pin places, leave reviews and rate places they visit. To be able to modify or remove any of the mentioned before. To establish a network of contacts that can access their content as well as being able to access those contact's information. To be able to revoke connections and to stop sharing information with them. To access public content posted by any other user / organization. To create several custom maps. To filter data displayed.
| Business Owner Users| Representative figure (CTO, CEO..) depending on the business. | (FURTHER STAGES OF THE PROGRAM) To be able to create map locations for their business, so potential visitors and customers can access them.
| Each city's council| Representative figure (Major, secretary, governor) depending on the location. | To boost the popularity and tourism of the city  , by making it easier for foreigners to discover good places. To give citizens a chance to discover new places. The application would have to complain certain specifications, for example, being secure.

| HappySw FrontEnd Engineers | Juan Manuel González Sierra, Manuel Hernández Cuartas, Sebastián Radu, Batuhan Bayir, Sara Fernández Arias  | They require to know the architecture in order to develop the user interface as well as to communicate it with other parts of the system. Also some constraints could take an effect on frontend decisions.
| HappySw Backend Engineers | Juan Manuel González Sierra, Manuel Hernández Cuartas, Sebastián Radu, Batuhan Bayir, Sara Fernández Arias | In order to develop lower layers of the design, such as data management and business logic, these engineers will require to know all aspects of the system's architecture.
| HappySw Testing Engineers |  Manuel Hernández Cuartas,Juan Manuel González Sierra, Manuel Hernández Cuartas, Sebastián Radu, Batuhan Bayir, Sara Fernández Arias | In order to test that the system is behaving as expected, engineers need to know how it is expected to work in the first place, and so, how not. For that, they'll need to have detailed knowledge about the system's architecture.

|  Existing SOLID-based applications  | Other group's members. See LoMap_enX or LoMap_esX on GitHub. Inrupt, & other pod providers.| To develop an application whose pods can communicate with other SOLID oriented applications.

|===
