[[section-introduction-and-goals]]
== Introduction and Goals
LoMap is an application designed for citizens in order to allow them to personalize their city map.

For that matter , users of LoMap will be allowed to do such things as leaving reviews of establishments, monuments or any other place of the city; as well as pinning those places they want to visit or have visited already.

LoMap will also be a tool for establishment owners to boost their businesses digitally by allowing them to have their own space on the map.

In brief, LoMap is more than a Map application , but a tool for cities to develop and offer their best to anybody that is interested in visiting them. Powered by its own inhabitants honest opinions, the city will open itself to outlanders allowing them to know places they probably would have never reached.
[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****

=== Requirements Overview


*All LoMap* Users will be able to:

* [x] Add locations and categorize them between a wide range of options, for example as restaurants or bars.
* [x] Leave reviews and multimedia of their experiences in such places.
* [x]  Stablish friendships , meaning that , they will be able to access all the contents other users label as friend-only.
    ** Users will be able to decide, then, if their posts are shared with all users, their friends only or remain accesible to themselves only.
* [x]  Filter the contents being displayed in the map by different parameters such as it being friend-content, it's  category...

In further of stages of the project, _stablishment owners & public entities_ will be able to:

* [x] create public map locations for their businesses


Keeping privacy in mind, all of the above, will be supported by the **SOLID project specification **, making use of **SOLID Pods ** for individual data storage. This way , users will be in full control of *which* information they share *and of who* they are sharing it to.

_More details are described in the following document: https://arquisoft.github.io/course2223/labAssignmentDescription.html[LoMap Assigment Description]_

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

=== Quality Goals

|===
|Goal | Description | Example

|Privacy
| Data will only be shared with those parties the owner agrees to.
| The user pins his/her own home in the map, and wants it to remain private, and not accesible to other users.
It will be stored in his/her own POD, and won't be shared with any other user nor party.

|Usability
| LoMap will be intuitive and easily used by both experienced and non-technical users. For that, naming, and content structuring  will be specially taken care of.
| User creates an account to record her favourite  city sight, and besides being elder &  non-technically skilled, she manages to create a pin succesfully , since the menu structure is intuitive and options are structured correctly. Hints and tips are provided too.


|Responsiveness
|LoMap will adapt it's size and content distribution to the device it's being accessed to, so usability is ensured.
|User want's to know the general opinion of a local restaurant of a city she's visiting. She owns an old , small-screened phone, and so , LoMap contents will change their layout so this user can navigate successfully though it.

|Maintainability
| Any improvements or changes will easily be performed. Also , It will be ensured that documentation is  updated as changes take place in code, so it's updated.
LoMap will be developed minding the readability of its code and documentation. Tests will be applied to each module in order to avoid unexpected failures and behaviors.
|A developer is  assigned to a task involved in a service whose development she has not participated at. She is able to perform her duty because she can understand the code and documentation solves most of her doubts.

|===

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name| Contact |Expectations
|Product owners| Professor José Emilio Labra Gayo.   | They'll provide the project with architectural guidance, constraints and requirements.
| Citizen Users| - | To be able to intuitively pin places, leave reviews and rate places they visit. To be able to modify or remove any of the mentioned before. To establish a network of contacts that can access their content as well as being able to access those contact's information. To be able to revoke connections and to stop sharing information with them. To access public content posted by any other user / organization. To create several custom maps. To filter data displayed.
| Business Owner Users| Representative figure (CTO, CEO..) depending on the business. | (FURTHER STAGES OF THE PROGRAM) To be able to create map locations for their business, so potential visitors and customers can access them.
| Each city's council| Representative figure (Major, secretary, governor) depending on the location. | To boost the popularity and tourism of the city  , by making it easier for foreigners to discover good places. To give citizens a chance to discover new places. The application would have to complain certain specifications, for example, being secure.

| HappySw FrontEnd Engineers | Juan Manuel González Sierra, Manuel Hernández Cuartas, Sebastián Radu, Batuhan Bayir, Sara Fernández Arias  | They require to know the architecture in order to develop the user interface as well as to communicate it with other parts of the system. Also some constraints could take an effect on frontend decisions.
| HappySw Backend Engineers | Juan Manuel González Sierra, Manuel Hernández Cuartas, Sebastián Radu, Batuhan Bayir, Sara Fernández Arias | In order to develop lower layers of the design, such as data management and business logic, these engineers will require to know all aspects of the system's architecture.
| HappySw Testing Engineers |  Manuel Hernández Cuartas,Juan Manuel González Sierra, Manuel Hernández Cuartas, Sebastián Radu, Batuhan Bayir, Sara Fernández Arias | In order to test that the system is behaving as expected, engineers need to know how it is expected to work in the first place, and so, how not. For that, they'll need to have detailed knowledge about the system's architecture.
|  Map/ geodatabase provider |Support of the provider (To be decided)| The provider of all map-related elements. We need to know their own api and probably some architecture aspects and constraints, to be able to comunicate with their services and to integrate their data into our app.
|  Existing SOLID-based applications  | Other group's members. See LoMap_enX or LoMap_esX on GitHub. | To develop an application whose pods can communicate with other SOLID oriented applications.

|===
