[[section-system-scope-and-context]]
== System Scope and Context
LoMap is a Software system where citizens can hav personalised maps about places and locals businesses in their city. The personalised maps will be under full control of the users and the shared information will be stored in a personal pod according to the SOLID project. 

LoMap is a generic software solution that can be deployed and used in other cities. It is focus on the user but it also allows places to create their own space, like a digital version of their physical place.


[role="arc42help"]
****
.Contents
System scope and context - as the name suggests - delimits your system (i.e. your scope) from all its communication partners
(neighboring systems and users, i.e. the context of your system). It thereby specifies the external interfaces.

If necessary, differentiate the business context (domain specific inputs and outputs) from the technical context (channels, protocols, hardware).

.Motivation
The domain interfaces and technical interfaces to communication partners are among your system's most critical aspects. Make sure that you completely understand them.

.Form
Various options:

* Context diagrams
* Lists of communication partners and their interfaces.
****


=== Business Context

[role="arc42help"]
****
.Contents
Specification of *all* communication partners (users, IT-systems, ...) with explanations of domain specific inputs and outputs or interfaces.
Optionally you can add domain specific formats or communication protocols.

.Motivation
All stakeholders should understand which data are exchanged with the environment of the system.

.Form
All kinds of diagrams that show the system as a black box and specify the domain interfaces to communication partners.

Alternatively (or additionally) you can use a table.
The title of the table is the name of your system, the three columns contain the name of the communication partner, the inputs, and the outputs.
****

LoMap software manages information from user’s POD and displays information from places in a map. In order to do that it need a map to display and a way to access to the user’s data.

Since it is a generic software solution, it communicates with two partners to satisfy this requirements.

First we need a map provider, that is because we want LoMap to be flexible to changes so we can change the city it displays without needing a big database with all this data stored by our system. And second, a POD Manager, that will help us with authentication and data manipulation.

**Business context’s diagram**
[plantuml,"Business Context diagram",png]
----
actor User as S 
rectangle “LoMap” as System 
rectangle “Map Provider” as MapAPI 
rectangle “POD Provider (API)” as PodAPI
S --> System: uses 
System --> PodAPI: location 
PodAPI --> System: map 
System --> MapAPI: request 
MapAPI --> System: data 
----
**External domain interfaces**
We have decided to two Mapping APIs; an open-source JavaScript library (Leaflet) for the mapping features and open licence map provider (OpenStreetMap). And for managing the user’s data a React’s library that uses the Inrupt Javascript Client Libraries (Solid React SDK - solid-ui-react).

|===
|Communication partner|Inputs|Outputs
| Google
    | geographical coordinates and a zoom level
    | map object
| solid-ui-react (Inrupt)
    | podURL, session
    | datasets/things
|===
=== Technical Context


We decided to use the MERN architecture.

MERN  uses a 3-tier architecture comprising the front end, the back end, and a database. React is in charge of the Front-End. You then have Node and Express for the back end or server-side. Finally, MongoDB is the database chosen for this stack. These components use JavaScript and JSON (JavaScript Object Notation) to create web applications.


One of the goals is the decentralization of the application. This is done thanks to the PODs that will help us to ensure user’s privacy.

Users are the ones that own and manage the access to their information, not the application itself. To handle this, each user will be the owner of a Solid POD (Personal Online Data Store) from which the required information is extracted.



|===
|Technology|Explication
| React | React is a free and open-source front-end JavaScript library for building user interfaces based on components. We use it to develop the website in frontend.
| JavaScript | Is the programming language used for the development. It is one of the core technologies of the World Wide Web.
| SOLID | Is used to store each users data in a POD.
|===







[role="arc42help"]
****
.Contents
Technical interfaces (channels and transmission media) linking your system to its environment. In addition a mapping of domain specific input/output to the channels, i.e. an explanation with I/O uses which channel.

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****
