[[section-solution-strategy]]
== Solution Strategy
1. Implement LoMap in the MERN (MongoDB, Express, React, Node) framework.
2. Use MongoDB in order to implement a database for the storage of non-private information.
3. Private information stored in pods.
4. Apply a modular monolithic architecture (client-modular server-database and pods).
5. Use Google Maps API regarding the maps of the application.
6. Use the corresponding APIs in order to establish proper connection with the pods.


[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****
