[[section-solution-strategy]]

=== Technology decisions
* Implement LoMap in the (Express, React, Node) framework. LoMap will be a webapp, therefore we need a nice framework for developing fullstack applications. Also React is a really suitable framework for the use of the pods.

=== Decisions about the top-level decomposotion of the system
* Apply a modular monolithic architecture (client-modular server-database and pods). Although we are not having just a source of data due to the use of pods.

=== Decisions on how to achieve key quality goals
* Private information stored in pods. Key aspect regarding the individual data of the users.
* Use Google Maps API regarding the maps of the application. Brings us a nice infrastructure regarding every location aspect of the application we could need.
* Use the corresponding APIs in order to establish proper connection with the pods. 

=== Decisions on how to achieve key quality goals
* Use of git workflow regarding version control. This way we can have a great amount of control over the versioning and updating of the code when developing the application.
* Constant review and update of the projects documentation in order to develop an easy to understand application for other developers (not only potential users).
* Forget about using a centralised DataBase and a RestAPI. This will help to keep user's data private since it will only use the SOLID POD.


[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****
