[[section-runtime-view]]
== Runtime View

[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

_All runtime scenarios where developed based on the http://solid.georgetown.domains/technical-component/[SOLID project documentation_]

=== <Runtime Scenario 1 - User login>

* The user logs into LoMap, by using his POD credentials.
** Credentials will be validated by making a petition to the POD provider (INRUPT) api
*** LoMap checks the session's Login status.
    **** If the data is correct, a new session will be started, and lomap will display the user's map.
    **** In case the data is not found, user will be notified. No session will start.


[plantuml,"UserLogin",png]
----
@startuml
title User Logs Into LoMap
actor User
participant "LoMap"
participant "Maps Api" as maps
participant "Inrupt solid-client API" as InruptApi
database "POD"
group User Login
User-> LoMap: https://www.lomap.com
activate LoMap
LoMap--> User: LogInForm.html
User->LoMap : Login(userId,password)
LoMap-> InruptApi : getPodId(credentials)
activate InruptApi
InruptApi--> LoMap : POD's Id
LoMap -> LoMap : Creates session that stores POD'S id
LoMap -> InruptApi: asks for POD's data using id
deactivate LoMap
InruptApi-> POD : asks for data
activate POD
POD--> InruptApi : shares data
deactivate POD
InruptApi--> LoMap : responds with data from POD
activate LoMap
LoMap-> maps: gets base map
maps--> LoMap : returns map
LoMap-> LoMap : adds POD's info to map render
deactivate InruptApi
LoMap -> User : User's personal map
deactivate LoMap
end
@enduml
----

=== <Runtime Scenario 2 - User adds private elements to the map>
Location Addition Deletion & Updating will work in a similar way architecture-wise. In general terms, the process will be the following :

    * Petition to the Inrupt api using the POD's ID.

    * Inrupt api will communicate with the pod, depending on the endpoint, it will ask the pod to add, update , delete or just retrieve information.

    * In case of addition/deletion/update , LoMap will ask the POD to return the updated data (through Inrupts api)

    * Once LoMap receives the updated data, the map will be rendered again.

_Below, a sequence diagram for Additions it's provided_
[plantuml,"UserCustomizesPrivateMapPrivate",png]
----
@startuml
title Insertion of new private location
actor "Authenticated user" as User
participant "LoMap"
participant "Maps Api" as maps
participant "Inrupt solid-client API" as InruptApi
database "POD"
group User adds  a private Location
User-> LoMap: Adds Location
activate LoMap
LoMap-> LoMap : gets POD's ID stored in session
LoMap -> InruptApi: asks to add data to the pod of the ID
deactivate LoMap
activate InruptApi
InruptApi-> POD : asks pod to insert new  location data
activate POD
POD --> InruptApi : notifies that data was inserted successfully
deactivate POD
LoMap-> InruptApi : asks for the POD's locations

activate LoMap
InruptApi-> POD : asks for the updated set of private map locations
POD--> InruptApi : shares updated map locations
deactivate POD
InruptApi--> LoMap:Returns POD's locations (now updated)
deactivate InruptApi
LoMap-> maps: asks for base map
activate maps
maps--> LoMap : returns map
deactivate maps
LoMap-> LoMap : adds POD's info to map render

deactivate InruptApi

LoMap --> User :Displays User's personal map
deactivate LoMap
end
@enduml

----
_For the sake of simplicity, friend's locations CRUD & display will be covered in an independent runtime scenario._

=== <Runtime Scenario 4 - Friend >
[plantuml,"UserCreatesRoute",png]
----
@startuml

title LoMap APP Sequence Diagram
actor User
participant "LoMap APP" as App
alt User creates route
    User -> App : Create Route
    App -> User : Display Route Info
else User compare maps
    User -> App : Compare Maps
    App -> User : Display Map Comparison Results
end
@enduml
----

=== <Runtime Scenario 5 - User checks address book>
[plantuml,"UserChecksAddressBook",png]
----
@startuml
title LoMap APP Sequence Diagram
actor User
participant "LoMap APP" as App
alt User check address book
    User -> App : Check Address Book
    App -> User : Display Place Recommendations
end
@enduml
----
=== <Runtime Scenario 6 - User Adds Friends/Groups>
[plantuml,"UserAddsFriends",png]
----
@startuml
title LoMap APP Sequence Diagram
actor User
participant "LoMap APP" as App
alt User adds friends/groups
    User -> App : Add Friends/Groups
    App -> User : Display Friends/Groups Info
else User views newsfeed
    User -> App : View Newsfeed
    App -> User : Display Newsfeed with Connected Places
    end
@enduml
----

=== <Runtime Scenario 6 - Groups create Maps>
[plantuml,"GroupCreatesMap",png]
----
@startuml
title LoMap APP Sequence Diagram
actor Group
participant "LoMap APP" as App
alt Group adds Maps
    Group -> App : Add Maps
    App -> Group : Display Maps with Locations
    else Group choose Role
    Group -> App : chose role (family maps, tourist groups, etc. )
    App -> Group : Display role Info
    end
    @enduml
----

=== <Runtime Scenario 7  - User(business owners) Create a Map>
[plantuml," businessOwnerCreatesMap",png]
----
@startuml
title LoMap APP Sequence Diagram
actor User
participant "LoMap APP" as App
alt User(business owners) create a map
    User -> App : business owners:create a map with recommended places near their own store (like other stores, or bars to chill after shopping, etc…)
    App -> User :  Display Maps with Locations
    end
 @enduml
----


=== <Runtime Scenario 8-Places create their pods>
[plantuml,"placesCreateTheirOwnPods",png]
----
@startuml
title LoMap APP Sequence Diagram
actor User
actor Group
actor Places
participant "LoMap APP" as App
alt Places create their own pods
Places -> App : (restaurants, shops, bars, etc.) to create their own pods
User -> Places : can connect to them
Group -> Places : can connect to them
else App creates Newsfedd from connected places
App -> User : Create a newsfeed from connected places
App -> Group : Create a newsfeed from connected places
end
@enduml
----



