[[section-runtime-view]]
== Runtime View

[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

_All runtime scenarios where developed based on the http://solid.georgetown.domains/technical-component/[SOLID project documentation_]

=== <Runtime Scenario 1 - User login>

* The user logs into LoMap, by using his POD credentials.
** Credentials will be validated by making a petition to the POD provider (INRUPT) api
*** LoMap checks the session's Login status.
    **** If the data is correct, a new session will be started, and lomap will display the user's map.
    **** In case the data is not found, user will be notified. No session will start.


[plantuml,"UserLogin",png]
----
@startuml
title User Logs Into LoMap
actor User
participant "LoMap"
participant "Maps Api" as maps
participant "Inrupt solid-client API" as InruptApi
database "POD"
group User Login
User-> LoMap: https://www.lomap.com
activate LoMap
LoMap--> User: LogInForm.html
User->LoMap : Login(userId,password)
LoMap-> InruptApi : getPodId(credentials)
activate InruptApi
InruptApi--> LoMap : POD's Id
LoMap -> LoMap : Creates session that stores POD'S id
LoMap -> InruptApi: asks for POD's data using id
deactivate LoMap
InruptApi-> POD : asks for data
activate POD
POD--> InruptApi : shares data
deactivate POD
InruptApi--> LoMap : responds with data from POD
activate LoMap
LoMap-> maps: gets base map
maps--> LoMap : returns map
LoMap-> LoMap : adds POD's info to map render
deactivate InruptApi
LoMap -> User : User's personal map
deactivate LoMap
end
@enduml
----

=== <Runtime Scenario 2 - User adds private elements to the map>
Location Addition Deletion & Updating will work in a similar way architecture-wise. In general terms, the process will be the following :

    * Petition to the Inrupt api using the POD's ID.

    * Inrupt api will communicate with the pod, depending on the endpoint, it will ask the pod to add, update , delete or just retrieve information.

    * In case of addition/deletion/update , LoMap will ask the POD to return the updated data (through Inrupts api)

    * Once LoMap receives the updated data, the map will be rendered again.

_Below, a sequence diagram for Additions it's provided_
[plantuml,"UserCustomizesPrivateMapPrivate",png]
----
@startuml
title Insertion of new private location
actor "Authenticated user" as User
participant "LoMap"
participant "Maps Api" as maps
participant "Inrupt solid-client API" as InruptApi
database "POD"
group User adds  a private Location
User-> LoMap: Adds Location
activate LoMap
LoMap-> LoMap : gets POD's ID stored in session
LoMap -> InruptApi: asks to add data to the pod of the ID
deactivate LoMap
activate InruptApi
InruptApi-> POD : asks pod to insert new  location data
activate POD
POD --> InruptApi : notifies that data was inserted successfully
deactivate POD
LoMap-> InruptApi : asks for the POD's locations

activate LoMap
InruptApi-> POD : asks for the updated set of private map locations
POD--> InruptApi : shares updated map locations
deactivate POD
InruptApi--> LoMap:Returns POD's locations (now updated)
deactivate InruptApi
LoMap-> maps: asks for base map
activate maps
maps--> LoMap : returns map
deactivate maps
LoMap-> LoMap : adds POD's info to map render

deactivate InruptApi

LoMap --> User :Displays User's personal map
deactivate LoMap
end
@enduml

----
_For the sake of simplicity, friend's locations CRUD & display will be covered in an independent runtime scenario._

=== <Runtime Scenario 4 -Privacy levels >
LoMap will provide the users with** TWO privacy levels at the moment**:

    * *Friends-Only* posts will _only_ be displayed to _their contacts_

    * *Private* contributions will appear _to the creator only._

In *further stages,* a new privacy level will be implemented:

* *Public* contributions to the map will be shown to _any_ user.


*The references to Friend  users are stored in the Pod*

 * That means that, to display friend content, a petition to the pod will be made to ask for the set of friends of a user.

    **  LoMap will retrieve the locations set as friend-only  by each contact from the pod and then add them to the user's personal rendered map.

[plantuml,"FriendsContent",png]
----
@startuml
title Map & Friends-Only content

actor "Authenticated user" as User
actor "User's Friend" as Friend
participant "LoMap"
participant "Maps Api" as maps
participant "Inrupt solid-client API" as InruptApi
database "POD" as pod

group User interactions

group user adds friend-only location
    User-> LoMap: Adds Location as friend Only
    activate LoMap #LightBlue

    LoMap-> LoMap : gets user's POD ID stored in session

    LoMap -> InruptApi: petition to insert location in the POD
    activate InruptApi
    InruptApi -> pod:Insert location with friend-only privacy
    deactivate InruptApi
    deactivate LoMap

end
note over InruptApi
       When a user witnesses the map , it will show:
            -Friends-Only posts by their contacts
            -their own private and friend-only contributions to the map.
    end note
group other (friend) user sees their personal map

Friend->LoMap: logs in
activate LoMap #LightBlue
LoMap-> maps: asks for base map
activate maps #gold
maps--> LoMap : returns map
deactivate maps
LoMap-> InruptApi : asks for the related POD's IDs (friends)
activate InruptApi#darkviolet
InruptApi-> pod : asks for friend's POD's IDs
activate pod #orchid
pod--> InruptApi : shares friends' IDs.
deactivate pod
InruptApi--> LoMap:Returns POD's friends (set of IDs)
deactivate InruptApi
loop for each friend id

    LoMap->InruptApi:ask for friend's locations shared
    activate InruptApi#darkviolet
    InruptApi-->LoMap: returns friend's locations
    LoMap->LoMap: adds locations to map's render
end loop


LoMap->LoMap: adds locations to map's render
deactivate InruptApi
LoMap --> Friend :Displays personal map
Friend->LoMap:interacts with authUser's location
deactivate LoMap

end
legend right
    | COLOR | ACTIVITY |
    |<#LightBlue>| LoMap |
    |<#gold>| Maps API |
    |<#darkviolet>| INRUPT API |
    |<#orchid>| SOLID PODS |
endlegend

@enduml

----
