[[section-runtime-view]]
== Runtime View

[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== <Runtime Scenario 1>

* _<insert runtime diagram or textual description of the scenario>_
* _<insert description of the notable aspects of the interactions between the
building block instances depicted in this diagram.>_

It is possible to use a sequence diagram:

[plantuml,"Sequence diagram",png]
----
actor Alice
actor Batu
database Pod as "Batu's Pod"
Alice -> Batu: Authentication Request
Batu --> Alice: Authentication Response
Alice  --> Pod: Store route
Alice ->Batu: Another authentication Request
Alice <-- Batu: another authentication Response
----
=== <Runtime Scenario 2>

=== ...

=== <Sequance Diagram // User Login>
[plantuml,"Sequance Diagram // User Login",png]
----
@startuml
title LoMap APP Sequence Diagram
actor User
participant "LoMap APP" as App
alt User Login
User -> App : Login
App -> User : Display Home Page
end
@enduml
----

=== <Sequance Diagram // User Choose a Role>
[plantuml,"Sequance Diagram // User Choose a Role",png]
----
@startuml
title LoMap APP Sequence Diagram
actor User
participant "LoMap APP" as App
alt User choose a Role
App -> User : Add different roles (citizen, tourist visitor, business owner)
User -> App : choose a role (citizen, tourist visitor, business owner)
App -> User : Display role info
end
@enduml
----

=== <Sequance Diagram // User Add Location>
[plantuml,"Sequance Diagram // User Add Location",png]
----
@startuml
title LoMap APP Sequence Diagram
actor User
participant "LoMap APP" as App
alt User Adds Locations
    User -> App : Add Locations
    App -> User : Display Locations Details
    User -> App : Add Reviews/Comments/Pictures
    App -> User : Confirm Added Info
    else User Views Maps
    User -> App : View Maps
    App -> User : Display Maps with Locations
end
@enduml
----

=== <Sequance Diagram // User Creates Route>
[plantuml,"Sequance Diagram // User Creates Route",png]
----
@startuml
title LoMap APP Sequence Diagram
actor User
participant "LoMap APP" as App
alt User creates route
    User -> App : Create Route
    App -> User : Display Route Info
else User compare maps
    User -> App : Compare Maps
    App -> User : Display Map Comparison Results
end
@enduml
----

=== <Sequance Diagram // User Check Address Book>
[plantuml,"Sequance Diagram // User Check Address Book",png]
----
@startuml
title LoMap APP Sequence Diagram
actor User
participant "LoMap APP" as App
alt User check address book
    User -> App : Check Address Book
    App -> User : Display Place Recommendations
end
@enduml
----

=== <Sequance Diagram // User Check Address Book>
[plantuml,"Sequance Diagram // User Check Address Book",png]
----
@startuml
title LoMap APP Sequence Diagram
actor User
participant "LoMap APP" as App
alt User check address book
    User -> App : Check Address Book
    App -> User : Display Place Recommendations
end
@enduml
----

=== <Sequance Diagram // User Adds Friends/Groups>
[plantuml,"Sequance Diagram // User Adds Friends/Groups",png]
----
@startuml
title LoMap APP Sequence Diagram
actor User
participant "LoMap APP" as App
alt User adds friends/groups
    User -> App : Add Friends/Groups
    App -> User : Display Friends/Groups Info
else User views newsfeed
    User -> App : View Newsfeed
    App -> User : Display Newsfeed with Connected Places
    end
@enduml
----

=== <Sequance Diagram // Group adds Maps>
[plantuml,"Sequance Diagram // Group adds Maps",png]
----
@startuml
title LoMap APP Sequence Diagram
actor Group
participant "LoMap APP" as App
alt Group adds Maps
    Group -> App : Add Maps
    App -> Group : Display Maps with Locations
    else Group choose Role
    Group -> App : chose role (family maps, tourist groups, etc. )
    App -> Group : Display role Info
    end
    @enduml
----

=== <Sequance Diagram // User(business owners) Create a Map>
[plantuml,"Sequance Diagram // User(business owners) Create a Map",png]
----
@startuml
title LoMap APP Sequence Diagram
actor User
participant "LoMap APP" as App
alt User(business owners) create a map
    User -> App : business owners:create a map with recommended places near their own store (like other stores, or bars to chill after shopping, etc…)
    App -> User :  Display Maps with Locations
    end
 @enduml
----

=== <Sequance Diagram // Adds Gamification Features>
[plantuml,"Sequance Diagram // Adds Gamification Features",png]
----
@startuml
title LoMap APP Sequence Diagram
actor User
participant "LoMap APP" as App
alt App adds gamification features
App -> User : Add gamification features (e.g. collect places, discover new ones etc.)
User -> App : Play games
end
@enduml
----

=== <Sequance Diagram // Places Create Their Own Pods>
[plantuml,"Sequance Diagram // Places Create Their Own Pods",png]
----
@startuml
title LoMap APP Sequence Diagram
actor User
actor Group
actor Places
participant "LoMap APP" as App
alt Places create their own pods
Places -> App : (restaurants, shops, bars, etc.) to create their own pods
User -> Places : can connect to them
Group -> Places : can connect to them
else App creates Newsfedd from connected places
App -> User : Create a newsfeed from connected places
App -> Group : Create a newsfeed from connected places
end
@enduml
----



