[[section-deployment-view]]


== Deployment View

[role="arc42help"]
****
.Content
The deployment view describes:

 1. the technical infrastructure used to execute your system, with infrastructure elements like geographical locations, environments, computers, processors, channels and net topologies as well as other infrastructure elements and

2. the mapping of (software) building blocks to that infrastructure elements.

Often systems are executed in different environments, e.g. development environment, test environment, production environment. In such cases you should document all relevant environments.

Especially document the deployment view when your software is executed as distributed system with more then one computer, processor, server or container or when you design and construct your own hardware processors and chips.

From a software perspective it is sufficient to capture those elements of the infrastructure that are needed to show the deployment of your building blocks. Hardware architects can go beyond that and describe the infrastructure to any level of detail they need to capture.

.Motivation
Software does not run without hardware.
This underlying infrastructure can and will influence your system and/or some
cross-cutting concepts. Therefore, you need to know the infrastructure.

.Form

Maybe the highest level deployment diagram is already contained in section 3.2. as
technical context with your own infrastructure as ONE black box. In this section you will
zoom into this black box using additional deployment diagrams:

* UML offers deployment diagrams to express that view. Use it, probably with nested diagrams,
when your infrastructure is more complex.
* When your (hardware) stakeholders prefer other kinds of diagrams rather than the deployment diagram, let them use any kind that is able to show nodes and channels of the infrastructure.
****

=== Infrastructure Level 1

[role="arc42help"]
****
Describe (usually in a combination of diagrams, tables, and text):

*  the distribution of your system to multiple locations, environments, computers, processors, .. as well as the physical connections between them
*  important justification or motivation for this deployment structure
* Quality and/or performance features of the infrastructure
*  the mapping of software artifacts to elements of the infrastructure

For multiple environments or alternative deployments please copy that section of arc42 for all relevant environments.
****

_**<Overview Diagram>**_

[plantuml,"DeploymentOverview",png]

----
@startuml
node "client" <<device>>{
[Client's Web browser]
}
node "Github  server" <<device>> as repo{
cloud "LoMAP deployment" as dep{
    package "User interface"{
       [ "UI" ] as ui
    }
    package "Business Logic" as business{
        [ "Location management " ]
        ["User management "]
        ["Friendship management "]
    }
   }

}
node "Azure Virtual Machine " <<device>> as lomap {
cloud "LoMAP execution enviroment" as env{
    [Lomap container]
}
}
node "Google Maps' Server" <<device>> as maps{
    [Google Maps JS API]
}

node " Inrupt server" <<device>> as inrupt{
  ["Solid Client Api"] as api
    cloud "Pods enviroment" as pods{
database "USER1'S POD "
    database "USER2'S POD "
    database "USER3'S POD "
    database "USER4'S POD "
    database "USER5'S POD "
    database "USER6'S POD "
    database "USER7'S POD "
    database "USER8'S POD "
    database "USERn'S POD"
}


}






client-down->lomap
lomap-down-repo
repo-down->maps

repo-right->inrupt

api<->pods

@enduml

----

Motivation::
In order to provide clients with a better understanding of the communication between system modules.


Quality and/or Performance Features::

We've chosen these modules in order to keep architecture easier to maintain , and therefore to have more control over attributes as privacy , scalability..


Mapping of Building Blocks to Infrastructure::

|===
|Element | Description

|Render
| Hosting service

|GitHub
|Repository where LoMap's source code is stored.

|MongoDb
|LoMap's database for public information

|Business Logic
|Set of LoMap's application modules.

|User interface
| Frontend of the application that will communicate with pod provider's and user IO

|Solid client api
|Inrupt's api LoMap will use to communicate with pods.


|===

