[[section-design-decisions]]
== Design Decisions


[role="arc42help"]
****
.Contents
Important, expensive, large scale or risky architecture decisions including rationals.
With "decisions" we mean selecting one alternative based on given criteria.

Please use your judgement to decide whether an architectural decision should be documented
here in this central section or whether you better document it locally
(e.g. within the white box template of one building block).

Avoid redundancy. Refer to section 4, where you already captured the most important decisions of your architecture.

.Motivation
Stakeholders of your system should be able to comprehend and retrace your decisions.

.Form
Various options:

* List or table, ordered by importance and consequences or:
* more detailed in form of separate sections per decision
* ADR (architecture decision record) for every important decision
****

=== Architectural Decision Record


|===
|Decision| Description

|Using a MERN STACK
|  Horizontal scalability . Good choice for real-time apps.
|Using Render as a hosting service
| Offers free hosting with integrated continuous deployment. Https granted too.
|Having two privacy levels : Just for friends and private.
| To allow the user to decide which people he/she shares the locations with.
|Using Just React and Express
|We will rely on solid pods, so we don't need to provide an api + Privacy.
|Folder structure
|We will take advantage of the pods folders "public" & "private". Inside each one we will create the folder for the private section of lomap, and the folder for the locations shared with friends.
|Usage of Azure as a hosting service
|Render required organization permissions to apply continuous integration since it was a third part app. Azure is just fine for the time our app will be deployed.

|===

=== Folder structure
In order to avoid collisions with other lomap applications, and so , allow our users to be able to use several LoMap solutions, we have thought of the following

    POD:
        Public:
            --LoMapEn3b:
                --Pictures:
                    -beach.png
                --Locations.ttl
                --Reviews.ttl
        Private:
            --LoMapEn3b:
                --Pictures:
                    -Selfie.png
                --Locations.ttl
                --Reviews.ttl

=== Friends
The app description does not provide a clear definition of what 'friends' means. We have decided that the system's
friends will be the user's friends in their POD's provider.

This decision was made to ensure that the app is easy and convenient to use for our target users, as they would already
be familiar with their SOLID POD friends and would not need to spend extra time creating new friend groups within the app.
It prioritizes the user privacy and data security.

=== Hosting service
Regarding hosting services , we've  balanced the following options:

|===
|Hosting service | Pros | cons | Using it would imply...

|Heroku
| Used to offer free hosting
| Not free hosting offered anymore
| Paying - immediately rejected.

|FireBase
| Security.

SSL Certifcate.

Works nice with React.

Free hosting.
| Serverless ( for our architecture is a con)
| Since we don't plan on going serverless , we would have to connect to the DB from the client using JS. Messy. Specially risky, since SOLID PODS require https.
    Other option is to go serverless.

|Azure
| Free credits given by university.

We used it already.

Security.

Compatibility.
| Credit card info has to be provided even for free services.

Machines consume credit each minute being used, and in order to spend 0 credits we would need to delete the machines.
| Being really mindful of credit left.
We are not really sure if it would be compatible with continuous deployment, since that would require the service to be working. We would probably run out of credit.

| Amazon Web Services
|
     Free credits given by university.

     Used it in SEW.

     Security.

    Compatibility.

    Load Balancing & CDN

| The free version is not what it used to be, now , part of the credit has to be used to take some courses aws provides , not to spend it in personal projects. So that would probably end up in credit running out.

| Being really mindful of credit left. Having to make the tutorials. Just like azure, we are not really sure if it would be compatible with continuous deployment, since that would require the service to be working. We would probably run out of credit.

| Netlify
|
    Free services

         300 build minutes/month

          500 Websites can be hosted for free

         community forum

|   Only one member for free

| Only one person would be able to deploy and access the management UI. So each time someone of us wants to make a deploy, he/she would have to ask the person designed.



|===

We knew no option could be perfect, specially when looking for free services. But we also knew, these options were not the best fit they could be...At least not if we did not go serverless.

The option chosen was Azure. There, we will create a virtual machine , that will host a docker container running , made from an image of our application.

In order for it to be compatible with Inrupt, we will use port  443(https) to serve our application.

In order to enable the https certificates required , we will use certbot, letencrypt and docker volumes to map the required directories.

